# Generated by Django 3.1.3 on 2021-07-05 17:52

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.CharField(max_length=255)),
                ('day', models.DateField()),
                ('time', models.TimeField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='campaign', unique=True)),
                ('notes', models.TextField(blank=True)),
                ('dm_only', models.TextField(blank=True)),
                ('moon', models.CharField(choices=[('1', 'Lua Nova'), ('2', 'Lua Crescente'), ('3', 'Meia Lua'), ('4', 'Lua Gibosa'), ('5', 'Lua Cheia')], max_length=1)),
                ('moon_day', models.PositiveIntegerField()),
            ],
        ),
    ]
