# Generated by Django 3.1.3 on 2021-07-05 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gametable', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
