# Generated by Django 3.1.3 on 2021-07-05 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chars', '0029_auto_20210703_0144'),
        ('gametable', '0003_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleChar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'Aliados'), ('2', 'Inimigos')], max_length=1)),
                ('temp_health', models.IntegerField()),
                ('temp_rage', models.IntegerField()),
                ('temp_gnosis', models.IntegerField()),
                ('temp_will', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chars', to='gametable.game')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char_name', to='chars.character')),
            ],
        ),
    ]
