# Generated by Django 3.1.3 on 2021-07-05 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chars', '0029_auto_20210703_0144'),
        ('gametable', '0004_battlechar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlechar',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='char_name', to='chars.character'),
        ),
    ]
