# Generated by Django 3.1.3 on 2021-07-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gametable', '0007_auto_20210707_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='day',
            field=models.DateField(verbose_name='Dia'),
        ),
        migrations.AlterField(
            model_name='game',
            name='moon',
            field=models.CharField(choices=[('1', 'Lua Nova'), ('2', 'Lua Crescente Crescente'), ('3', 'Meia Lua Crescente'), ('4', 'Lua Gibosa Crescente'), ('5', 'Lua Cheia'), ('6', 'Lua Gibosa Minguante'), ('7', 'Meia Lua Minguante'), ('8', 'Lua Crescente Minguante')], max_length=1, verbose_name='Lua'),
        ),
        migrations.AlterField(
            model_name='game',
            name='moon_day',
            field=models.PositiveIntegerField(verbose_name='Dia da Lua'),
        ),
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.TimeField(verbose_name='Hora'),
        ),
    ]
