# Generated by Django 3.1.3 on 2021-07-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gametable', '0008_auto_20210708_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlechar',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
