# Generated by Django 3.1.3 on 2021-07-08 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gametable', '0009_auto_20210708_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='battlechar',
            options={'ordering': ('type', 'name')},
        ),
    ]
