# Generated by Django 3.1.3 on 2021-07-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gametable', '0010_auto_20210708_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rolls',
            field=models.TextField(blank=True, verbose_name='Rolagens'),
        ),
    ]
