# Generated by Django 3.1.3 on 2021-06-26 06:15

import autoslug.fields
import datetime
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 6, 26, 3, 15, 7, 737340))),
                ('body', models.TextField()),
                ('dm_only', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
