# Generated by Django 3.1.3 on 2021-06-26 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0002_auto_20210626_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='record',
            field=models.FileField(blank=True, upload_to='records'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 26, 3, 48, 8, 232618)),
        ),
    ]
