# Generated by Django 3.1.3 on 2021-06-29 02:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0004_auto_20210626_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 23, 18, 53, 242837)),
        ),
    ]
