# Generated by Django 3.1.3 on 2021-06-29 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0006_auto_20210629_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 29, 13, 54, 0, 323071)),
        ),
    ]
