# Generated by Django 3.1.3 on 2021-06-26 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group', to='chars.group'),
        ),
    ]
