# Generated by Django 3.1.3 on 2021-06-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chars', '0004_auto_20210629_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auspice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auspice', models.CharField(max_length=255, unique=True)),
                ('initial_rage', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(max_length=255)),
                ('breed', models.CharField(max_length=255)),
                ('initial_gnosis', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tribe', models.CharField(max_length=255, unique=True)),
                ('initial_will', models.PositiveIntegerField()),
                ('initial_attb', models.PositiveIntegerField()),
                ('initial_habl', models.PositiveIntegerField()),
            ],
        ),
    ]
