# Generated by Django 3.1.3 on 2021-06-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chars', '0005_auspice_race_tribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=255, unique=True)),
                ('initial_gift', models.PositiveIntegerField()),
                ('bonus', models.IntegerField()),
            ],
            options={
                'ordering': ('rank',),
            },
        ),
        migrations.AlterModelOptions(
            name='auspice',
            options={'ordering': ('initial_rage',)},
        ),
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ('initial_gnosis',)},
        ),
        migrations.AlterModelOptions(
            name='tribe',
            options={'ordering': ('tribe',)},
        ),
    ]
