# Generated by Django 3.1.3 on 2021-06-29 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chars', '0009_auto_20210629_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='lacerny',
            new_name='larceny',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='prime_urge',
            new_name='primal_urge',
        ),
    ]
