# Generated by Django 3.1.3 on 2021-07-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chars', '0011_auto_20210629_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('willpower_condition', models.TextField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
