# Generated by Django 3.1.3 on 2021-07-01 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chars', '0012_archetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='demeanor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demeanor', to='chars.archetype'),
        ),
        migrations.AddField(
            model_name='character',
            name='nature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nature', to='chars.archetype'),
        ),
    ]
