# Generated by Django 3.1.3 on 2021-07-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chars', '0013_auto_20210701_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[], max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='character',
            name='auspice',
        ),
        migrations.RemoveField(
            model_name='character',
            name='race',
        ),
        migrations.RemoveField(
            model_name='character',
            name='tribe',
        ),
        migrations.DeleteModel(
            name='Auspice',
        ),
        migrations.DeleteModel(
            name='Race',
        ),
        migrations.DeleteModel(
            name='Tribe',
        ),
    ]
