# Generated by Django 3.1.3 on 2021-07-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chars', '0014_auto_20210701_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('classfication', models.CharField(choices=[('1', 'Race'), ('2', 'Breed'), ('3', 'Auspice'), ('4', 'Tribe')], max_length=2)),
                ('initial_bonus', models.PositiveIntegerField()),
                ('initial_optional', models.PositiveIntegerField(blank=True)),
            ],
            options={
                'ordering': ('initial_bonus',),
            },
        ),
    ]
