# Generated by Django 3.1.3 on 2021-07-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chars', '0015_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='initial_optional',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
