# Generated by Django 3.1.3 on 2021-07-02 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chars', '0016_auto_20210701_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.ForeignKey(blank=True, limit_choices_to={'classfication': '1'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chars.type'),
        ),
    ]
