# Generated by Django 3.1.3 on 2021-07-02 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chars', '0017_character_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='auspice',
            field=models.ForeignKey(blank=True, limit_choices_to={'classfication': '3'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='char_auspice', to='chars.type'),
        ),
        migrations.AddField(
            model_name='character',
            name='breed',
            field=models.ForeignKey(blank=True, limit_choices_to={'classfication': '2'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='char_breed', to='chars.type'),
        ),
        migrations.AddField(
            model_name='character',
            name='tribe',
            field=models.ForeignKey(blank=True, limit_choices_to={'classfication': '4'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='char_tribe', to='chars.type'),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.ForeignKey(blank=True, limit_choices_to={'classfication': '1'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='char_race', to='chars.type'),
        ),
    ]
