# Generated by Django 3.1.3 on 2021-07-02 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chars', '0018_auto_20210701_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='cost',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='gift',
            name='duration',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='gift',
            name='effect',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gift',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gift',
            name='spirit_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='gift',
            name='test',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='gift',
            name='time',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='gift',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chars.type'),
        ),
    ]
