# Generated by Django 3.1.3 on 2021-07-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chars', '0019_auto_20210701_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='refference',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
