# Generated by Django 3.1.3 on 2021-07-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chars', '0020_gift_refference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gift',
            options={'ordering': ('level', 'name')},
        ),
        migrations.AddField(
            model_name='character',
            name='gifts',
            field=models.ManyToManyField(to='chars.Gift'),
        ),
    ]
