# Generated by Django 3.1.3 on 2021-07-02 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chars', '0022_auto_20210702_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rites',
            old_name='efect',
            new_name='effect',
        ),
    ]
