# Generated by Django 3.1.3 on 2021-07-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chars', '0023_auto_20210702_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='rite_list',
            field=models.ManyToManyField(to='chars.Rites'),
        ),
    ]
