# Generated by Django 3.1.3 on 2021-07-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chars', '0024_character_rite_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='gifts',
            field=models.ManyToManyField(blank=True, to='chars.Gift'),
        ),
        migrations.AlterField(
            model_name='character',
            name='rite_list',
            field=models.ManyToManyField(blank=True, to='chars.Rites'),
        ),
    ]
