# Generated by Django 3.1.3 on 2021-07-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chars', '0028_armor_item_weapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='armors',
            field=models.ManyToManyField(blank=True, to='chars.Armor'),
        ),
        migrations.AddField(
            model_name='character',
            name='itens',
            field=models.ManyToManyField(blank=True, to='chars.Item'),
        ),
        migrations.AddField(
            model_name='character',
            name='weapons',
            field=models.ManyToManyField(blank=True, to='chars.Weapon'),
        ),
    ]
