# Generated by Django 3.1.3 on 2021-07-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chars', '0029_auto_20210703_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='short_name',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
